package database

const commonSchema = `
CREATE TABLE IF NOT EXISTS schema_meta (
    key TEXT PRIMARY KEY NOT NULL,
    value TEXT NOT NULL
);
INSERT OR IGNORE INTO schema_meta (key, value) VALUES ('engine', 'sqlite');
INSERT OR IGNORE INTO schema_meta (key, value) VALUES ('schema_version', '1');
`

const authSchema = commonSchema + `
CREATE TABLE IF NOT EXISTS accounts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    ip TEXT NOT NULL DEFAULT '',
    gmlevel INTEGER NOT NULL DEFAULT 1,
    salt TEXT NOT NULL,
    verifier TEXT NOT NULL,
    sessionkey TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS realmlist (
    realm_id INTEGER PRIMARY KEY AUTOINCREMENT,
    realm_name TEXT NOT NULL DEFAULT '',
    proxy_address TEXT NOT NULL DEFAULT '0.0.0.0',
    proxy_port INTEGER NOT NULL DEFAULT 9090,
    realm_address TEXT NOT NULL DEFAULT '0.0.0.0',
    realm_port INTEGER NOT NULL DEFAULT 9100,
    online_player_count INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS applied_updates (
    id TEXT PRIMARY KEY NOT NULL DEFAULT '000000000'
);
INSERT OR IGNORE INTO realmlist (realm_id, realm_name, proxy_address, proxy_port, realm_address, realm_port, online_player_count)
VALUES (1, 'Moreno.AlphaCore', '0.0.0.0', 9090, '0.0.0.0', 9100, 0);
`

const realmSchema = commonSchema + `
CREATE TABLE IF NOT EXISTS characters (
    guid INTEGER PRIMARY KEY AUTOINCREMENT,
    account_id INTEGER NOT NULL DEFAULT 0,
    realm_id INTEGER NOT NULL DEFAULT 1,
    name TEXT NOT NULL DEFAULT '',
    race INTEGER NOT NULL DEFAULT 0,
    "class" INTEGER NOT NULL DEFAULT 0,
    gender INTEGER NOT NULL DEFAULT 0,
    level INTEGER NOT NULL DEFAULT 0,
    xp INTEGER NOT NULL DEFAULT 0,
    money INTEGER NOT NULL DEFAULT 0,
    skin INTEGER NOT NULL DEFAULT 0,
    face INTEGER NOT NULL DEFAULT 0,
    hairstyle INTEGER NOT NULL DEFAULT 0,
    haircolour INTEGER NOT NULL DEFAULT 0,
    facialhair INTEGER NOT NULL DEFAULT 0,
    bankslots INTEGER NOT NULL DEFAULT 0,
    talentpoints INTEGER NOT NULL DEFAULT 0,
    skillpoints INTEGER NOT NULL DEFAULT 0,
    position_x REAL NOT NULL DEFAULT 0,
    position_y REAL NOT NULL DEFAULT 0,
    position_z REAL NOT NULL DEFAULT 0,
    map INTEGER NOT NULL DEFAULT 0,
    orientation REAL NOT NULL DEFAULT 0,
    taximask TEXT,
    explored_areas TEXT,
    online INTEGER NOT NULL DEFAULT 0,
    totaltime INTEGER NOT NULL DEFAULT 0,
    leveltime INTEGER NOT NULL DEFAULT 0,
    extra_flags INTEGER NOT NULL DEFAULT 0,
    zone INTEGER NOT NULL DEFAULT 0,
    taxi_path TEXT,
    drunk INTEGER NOT NULL DEFAULT 0,
    health INTEGER NOT NULL DEFAULT 0,
    power1 INTEGER NOT NULL DEFAULT 0,
    power2 INTEGER NOT NULL DEFAULT 0,
    power3 INTEGER NOT NULL DEFAULT 0,
    power4 INTEGER NOT NULL DEFAULT 0,
    power5 INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS characters_name_idx ON characters (name);
CREATE INDEX IF NOT EXISTS characters_online_idx ON characters (online);
CREATE TABLE IF NOT EXISTS character_addons_settings (
    guid INTEGER PRIMARY KEY NOT NULL,
    flags INTEGER NOT NULL DEFAULT 0,
    settings TEXT,
    updated_at INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (guid) REFERENCES characters (guid) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS character_inventory (
    guid INTEGER PRIMARY KEY AUTOINCREMENT,
    owner INTEGER NOT NULL DEFAULT 0,
    creator INTEGER NOT NULL DEFAULT 0,
    bag INTEGER NOT NULL DEFAULT 0,
    slot INTEGER NOT NULL DEFAULT 0,
    item_template INTEGER NOT NULL DEFAULT 0,
    stackcount INTEGER NOT NULL DEFAULT 1,
    SpellCharges1 INTEGER NOT NULL DEFAULT -1,
    SpellCharges2 INTEGER NOT NULL DEFAULT -1,
    SpellCharges3 INTEGER NOT NULL DEFAULT -1,
    SpellCharges4 INTEGER NOT NULL DEFAULT -1,
    SpellCharges5 INTEGER NOT NULL DEFAULT -1,
    item_flags INTEGER NOT NULL DEFAULT 0,
    duration INTEGER NOT NULL DEFAULT 0,
    enchantments TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (owner) REFERENCES characters (guid) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS character_inventory_owner_idx ON character_inventory (owner);
CREATE TABLE IF NOT EXISTS character_spells (
    guid INTEGER NOT NULL,
    spell INTEGER NOT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    disabled INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (guid, spell),
    FOREIGN KEY (guid) REFERENCES characters (guid) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS character_buttons (
    owner INTEGER NOT NULL,
    "index" INTEGER NOT NULL,
    action INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (owner, "index", action),
    FOREIGN KEY (owner) REFERENCES characters (guid) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS character_spell_book (
    owner INTEGER NOT NULL,
    "index" INTEGER NOT NULL DEFAULT 0,
    spell INTEGER NOT NULL,
    PRIMARY KEY (owner, spell),
    FOREIGN KEY (owner) REFERENCES characters (guid) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS character_social (
    guid INTEGER NOT NULL,
    other_guid INTEGER NOT NULL,
    ignore INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (guid, other_guid, ignore),
    FOREIGN KEY (guid) REFERENCES characters (guid) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (other_guid) REFERENCES characters (guid) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "group" (
    group_id INTEGER PRIMARY KEY AUTOINCREMENT,
    leader_guid INTEGER NOT NULL,
    loot_method INTEGER NOT NULL DEFAULT 0,
    loot_master INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (leader_guid) REFERENCES characters (guid) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS group_member (
    group_id INTEGER NOT NULL,
    guid INTEGER NOT NULL,
    PRIMARY KEY (group_id, guid),
    FOREIGN KEY (group_id) REFERENCES "group" (group_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (guid) REFERENCES characters (guid) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS guild (
    guild_id INTEGER PRIMARY KEY AUTOINCREMENT,
    realm_id INTEGER NOT NULL DEFAULT 1,
    name TEXT NOT NULL DEFAULT '' UNIQUE,
    motd TEXT NOT NULL DEFAULT '',
    creation_date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    emblem_style INTEGER NOT NULL DEFAULT -1,
    emblem_color INTEGER NOT NULL DEFAULT -1,
    border_style INTEGER NOT NULL DEFAULT -1,
    border_color INTEGER NOT NULL DEFAULT -1,
    background_color INTEGER NOT NULL DEFAULT -1
);
CREATE TABLE IF NOT EXISTS guild_member (
    guild_id INTEGER NOT NULL,
    guid INTEGER NOT NULL,
    rank INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (guild_id, guid),
    FOREIGN KEY (guild_id) REFERENCES guild (guild_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (guid) REFERENCES characters (guid) ON DELETE CASCADE ON UPDATE CASCADE
);
`

const worldSchema = commonSchema + `
CREATE TABLE IF NOT EXISTS applied_updates (
    id TEXT PRIMARY KEY NOT NULL DEFAULT '000000000'
);
CREATE TABLE IF NOT EXISTS playercreateinfo (
    id INTEGER NOT NULL,
    race INTEGER NOT NULL DEFAULT 0,
    "class" INTEGER NOT NULL DEFAULT 0,
    map INTEGER NOT NULL DEFAULT 0,
    zone INTEGER NOT NULL DEFAULT 0,
    position_x REAL NOT NULL DEFAULT 0,
    position_y REAL NOT NULL DEFAULT 0,
    position_z REAL NOT NULL DEFAULT 0,
    orientation REAL NOT NULL DEFAULT 0,
    PRIMARY KEY (race, "class", id)
);
CREATE TABLE IF NOT EXISTS player_classlevelstats (
    "class" INTEGER NOT NULL,
    level INTEGER NOT NULL,
    basehp INTEGER NOT NULL DEFAULT 0,
    basemana INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY ("class", level)
);
CREATE TABLE IF NOT EXISTS playercreateinfo_item (
    id INTEGER NOT NULL,
    race INTEGER NOT NULL DEFAULT 0,
    "class" INTEGER NOT NULL DEFAULT 0,
    itemid INTEGER NOT NULL DEFAULT 0,
    amount INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS playercreateinfo_action (
    race INTEGER NOT NULL DEFAULT 0,
    "class" INTEGER NOT NULL DEFAULT 0,
    button INTEGER NOT NULL DEFAULT 0,
    action INTEGER NOT NULL DEFAULT 0,
    type INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (race, "class", button)
);
CREATE TABLE IF NOT EXISTS playercreateinfo_spell (
    race INTEGER NOT NULL DEFAULT 0,
    "class" INTEGER NOT NULL DEFAULT 0,
    Spell INTEGER NOT NULL DEFAULT 0,
    Note TEXT,
    PRIMARY KEY (race, "class", Spell)
);
CREATE TABLE IF NOT EXISTS item_template (
    entry INTEGER PRIMARY KEY NOT NULL,
    "class" INTEGER NOT NULL DEFAULT 0,
    subclass INTEGER NOT NULL DEFAULT 0,
    name TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    display_id INTEGER NOT NULL DEFAULT 0,
    quality INTEGER NOT NULL DEFAULT 0,
    flags INTEGER NOT NULL DEFAULT 0,
    buy_price INTEGER NOT NULL DEFAULT 0,
    sell_price INTEGER NOT NULL DEFAULT 0,
    inventory_type INTEGER NOT NULL DEFAULT 0,
    allowable_class INTEGER NOT NULL DEFAULT -1,
    allowable_race INTEGER NOT NULL DEFAULT -1,
    item_level INTEGER NOT NULL DEFAULT 0,
    required_level INTEGER NOT NULL DEFAULT 0,
    required_skill INTEGER NOT NULL DEFAULT 0,
    required_skill_rank INTEGER NOT NULL DEFAULT 0,
    max_count INTEGER NOT NULL DEFAULT 0,
    stackable INTEGER NOT NULL DEFAULT 1,
    container_slots INTEGER NOT NULL DEFAULT 0,
    stat_type1 INTEGER NOT NULL DEFAULT 0,
    stat_value1 INTEGER NOT NULL DEFAULT 0,
    stat_type2 INTEGER NOT NULL DEFAULT 0,
    stat_value2 INTEGER NOT NULL DEFAULT 0,
    stat_type3 INTEGER NOT NULL DEFAULT 0,
    stat_value3 INTEGER NOT NULL DEFAULT 0,
    stat_type4 INTEGER NOT NULL DEFAULT 0,
    stat_value4 INTEGER NOT NULL DEFAULT 0,
    stat_type5 INTEGER NOT NULL DEFAULT 0,
    stat_value5 INTEGER NOT NULL DEFAULT 0,
    stat_type6 INTEGER NOT NULL DEFAULT 0,
    stat_value6 INTEGER NOT NULL DEFAULT 0,
    stat_type7 INTEGER NOT NULL DEFAULT 0,
    stat_value7 INTEGER NOT NULL DEFAULT 0,
    stat_type8 INTEGER NOT NULL DEFAULT 0,
    stat_value8 INTEGER NOT NULL DEFAULT 0,
    stat_type9 INTEGER NOT NULL DEFAULT 0,
    stat_value9 INTEGER NOT NULL DEFAULT 0,
    stat_type10 INTEGER NOT NULL DEFAULT 0,
    stat_value10 INTEGER NOT NULL DEFAULT 0,
    delay INTEGER NOT NULL DEFAULT 1000,
    ammo_type INTEGER NOT NULL DEFAULT 0,
    dmg_min1 REAL NOT NULL DEFAULT 0,
    dmg_max1 REAL NOT NULL DEFAULT 0,
    dmg_type1 INTEGER NOT NULL DEFAULT 0,
    dmg_min2 REAL NOT NULL DEFAULT 0,
    dmg_max2 REAL NOT NULL DEFAULT 0,
    dmg_type2 INTEGER NOT NULL DEFAULT 0,
    dmg_min3 REAL NOT NULL DEFAULT 0,
    dmg_max3 REAL NOT NULL DEFAULT 0,
    dmg_type3 INTEGER NOT NULL DEFAULT 0,
    dmg_min4 REAL NOT NULL DEFAULT 0,
    dmg_max4 REAL NOT NULL DEFAULT 0,
    dmg_type4 INTEGER NOT NULL DEFAULT 0,
    dmg_min5 REAL NOT NULL DEFAULT 0,
    dmg_max5 REAL NOT NULL DEFAULT 0,
    dmg_type5 INTEGER NOT NULL DEFAULT 0,
    armor INTEGER NOT NULL DEFAULT 0,
    holy_res INTEGER NOT NULL DEFAULT 0,
    fire_res INTEGER NOT NULL DEFAULT 0,
    nature_res INTEGER NOT NULL DEFAULT 0,
    frost_res INTEGER NOT NULL DEFAULT 0,
    shadow_res INTEGER NOT NULL DEFAULT 0,
    spellid_1 INTEGER NOT NULL DEFAULT 0,
    spelltrigger_1 INTEGER NOT NULL DEFAULT 0,
    spellcharges_1 INTEGER NOT NULL DEFAULT 0,
    spellcooldown_1 INTEGER NOT NULL DEFAULT -1,
    spellcategory_1 INTEGER NOT NULL DEFAULT 0,
    spellcategorycooldown_1 INTEGER NOT NULL DEFAULT -1,
    spellid_2 INTEGER NOT NULL DEFAULT 0,
    spelltrigger_2 INTEGER NOT NULL DEFAULT 0,
    spellcharges_2 INTEGER NOT NULL DEFAULT 0,
    spellcooldown_2 INTEGER NOT NULL DEFAULT -1,
    spellcategory_2 INTEGER NOT NULL DEFAULT 0,
    spellcategorycooldown_2 INTEGER NOT NULL DEFAULT -1,
    spellid_3 INTEGER NOT NULL DEFAULT 0,
    spelltrigger_3 INTEGER NOT NULL DEFAULT 0,
    spellcharges_3 INTEGER NOT NULL DEFAULT 0,
    spellcooldown_3 INTEGER NOT NULL DEFAULT -1,
    spellcategory_3 INTEGER NOT NULL DEFAULT 0,
    spellcategorycooldown_3 INTEGER NOT NULL DEFAULT -1,
    spellid_4 INTEGER NOT NULL DEFAULT 0,
    spelltrigger_4 INTEGER NOT NULL DEFAULT 0,
    spellcharges_4 INTEGER NOT NULL DEFAULT 0,
    spellcooldown_4 INTEGER NOT NULL DEFAULT -1,
    spellcategory_4 INTEGER NOT NULL DEFAULT 0,
    spellcategorycooldown_4 INTEGER NOT NULL DEFAULT -1,
    spellid_5 INTEGER NOT NULL DEFAULT 0,
    spelltrigger_5 INTEGER NOT NULL DEFAULT 0,
    spellcharges_5 INTEGER NOT NULL DEFAULT 0,
    spellcooldown_5 INTEGER NOT NULL DEFAULT -1,
    spellcategory_5 INTEGER NOT NULL DEFAULT 0,
    spellcategorycooldown_5 INTEGER NOT NULL DEFAULT -1,
    bonding INTEGER NOT NULL DEFAULT 0,
    page_text INTEGER NOT NULL DEFAULT 0,
    page_language INTEGER NOT NULL DEFAULT 0,
    page_material INTEGER NOT NULL DEFAULT 0,
    start_quest INTEGER NOT NULL DEFAULT 0,
    lock_id INTEGER NOT NULL DEFAULT 0,
    material INTEGER NOT NULL DEFAULT 0,
    sheath INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS page_text (
    entry INTEGER PRIMARY KEY NOT NULL,
    text TEXT NOT NULL DEFAULT '',
    next_page INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS creature_template (
    entry INTEGER PRIMARY KEY NOT NULL,
    display_id1 INTEGER NOT NULL DEFAULT 0,
    name TEXT NOT NULL DEFAULT '',
    subname TEXT,
    static_flags INTEGER NOT NULL DEFAULT 0,
    level_min INTEGER NOT NULL DEFAULT 1,
    level_max INTEGER NOT NULL DEFAULT 1,
    faction INTEGER NOT NULL DEFAULT 0,
    scale REAL NOT NULL DEFAULT 1,
    unit_class INTEGER NOT NULL DEFAULT 1,
    unit_flags INTEGER NOT NULL DEFAULT 0,
    npc_flags INTEGER NOT NULL DEFAULT 0,
    type INTEGER NOT NULL DEFAULT 0,
    beast_family INTEGER NOT NULL DEFAULT 0,
    health_multiplier REAL NOT NULL DEFAULT 1,
    mana_multiplier REAL NOT NULL DEFAULT 1,
    armor_multiplier REAL NOT NULL DEFAULT 1,
    damage_multiplier REAL NOT NULL DEFAULT 1,
    damage_variance REAL NOT NULL DEFAULT 0.14,
    base_attack_time INTEGER NOT NULL DEFAULT 2000,
    ranged_attack_time INTEGER NOT NULL DEFAULT 2000
);
CREATE TABLE IF NOT EXISTS gameobject_template (
    entry INTEGER PRIMARY KEY NOT NULL,
    type INTEGER NOT NULL DEFAULT 0,
    displayId INTEGER NOT NULL DEFAULT 0,
    name TEXT NOT NULL DEFAULT '',
    faction INTEGER NOT NULL DEFAULT 0,
    flags INTEGER NOT NULL DEFAULT 0,
    size REAL NOT NULL DEFAULT 1,
    data0 INTEGER NOT NULL DEFAULT 0,
    data1 INTEGER NOT NULL DEFAULT 0,
    data2 INTEGER NOT NULL DEFAULT 0,
    data3 INTEGER NOT NULL DEFAULT 0,
    data4 INTEGER NOT NULL DEFAULT 0,
    data5 INTEGER NOT NULL DEFAULT 0,
    data6 INTEGER NOT NULL DEFAULT 0,
    data7 INTEGER NOT NULL DEFAULT 0,
    data8 INTEGER NOT NULL DEFAULT 0,
    data9 INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS quest_template (
    entry INTEGER PRIMARY KEY NOT NULL,
    Method INTEGER NOT NULL DEFAULT 2,
    ZoneOrSort INTEGER NOT NULL DEFAULT 0,
    QuestLevel INTEGER NOT NULL DEFAULT 0,
    Type INTEGER NOT NULL DEFAULT 0,
    NextQuestInChain INTEGER NOT NULL DEFAULT 0,
    SrcItemId INTEGER NOT NULL DEFAULT 0,
    RewOrReqMoney INTEGER NOT NULL DEFAULT 0,
    RewItemId1 INTEGER NOT NULL DEFAULT 0,
    RewItemId2 INTEGER NOT NULL DEFAULT 0,
    RewItemId3 INTEGER NOT NULL DEFAULT 0,
    RewItemId4 INTEGER NOT NULL DEFAULT 0,
    RewItemCount1 INTEGER NOT NULL DEFAULT 0,
    RewItemCount2 INTEGER NOT NULL DEFAULT 0,
    RewItemCount3 INTEGER NOT NULL DEFAULT 0,
    RewItemCount4 INTEGER NOT NULL DEFAULT 0,
    RewChoiceItemId1 INTEGER NOT NULL DEFAULT 0,
    RewChoiceItemId2 INTEGER NOT NULL DEFAULT 0,
    RewChoiceItemId3 INTEGER NOT NULL DEFAULT 0,
    RewChoiceItemId4 INTEGER NOT NULL DEFAULT 0,
    RewChoiceItemId5 INTEGER NOT NULL DEFAULT 0,
    RewChoiceItemId6 INTEGER NOT NULL DEFAULT 0,
    RewChoiceItemCount1 INTEGER NOT NULL DEFAULT 0,
    RewChoiceItemCount2 INTEGER NOT NULL DEFAULT 0,
    RewChoiceItemCount3 INTEGER NOT NULL DEFAULT 0,
    RewChoiceItemCount4 INTEGER NOT NULL DEFAULT 0,
    RewChoiceItemCount5 INTEGER NOT NULL DEFAULT 0,
    RewChoiceItemCount6 INTEGER NOT NULL DEFAULT 0,
    Title TEXT,
    Details TEXT,
    Objectives TEXT,
    EndText TEXT,
    PointMapId INTEGER NOT NULL DEFAULT 0,
    PointX REAL NOT NULL DEFAULT 0,
    PointY REAL NOT NULL DEFAULT 0,
    PointOpt INTEGER NOT NULL DEFAULT 0,
    ReqCreatureOrGOId1 INTEGER NOT NULL DEFAULT 0,
    ReqCreatureOrGOId2 INTEGER NOT NULL DEFAULT 0,
    ReqCreatureOrGOId3 INTEGER NOT NULL DEFAULT 0,
    ReqCreatureOrGOId4 INTEGER NOT NULL DEFAULT 0,
    ReqCreatureOrGOCount1 INTEGER NOT NULL DEFAULT 0,
    ReqCreatureOrGOCount2 INTEGER NOT NULL DEFAULT 0,
    ReqCreatureOrGOCount3 INTEGER NOT NULL DEFAULT 0,
    ReqCreatureOrGOCount4 INTEGER NOT NULL DEFAULT 0,
    ReqItemId1 INTEGER NOT NULL DEFAULT 0,
    ReqItemId2 INTEGER NOT NULL DEFAULT 0,
    ReqItemId3 INTEGER NOT NULL DEFAULT 0,
    ReqItemId4 INTEGER NOT NULL DEFAULT 0,
    ReqItemCount1 INTEGER NOT NULL DEFAULT 0,
    ReqItemCount2 INTEGER NOT NULL DEFAULT 0,
    ReqItemCount3 INTEGER NOT NULL DEFAULT 0,
    ReqItemCount4 INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS creature_classlevelstats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    "class" INTEGER NOT NULL DEFAULT 0,
    level INTEGER NOT NULL DEFAULT 0,
    melee_damage REAL NOT NULL DEFAULT 0,
    ranged_damage REAL NOT NULL DEFAULT 0,
    attack_power INTEGER NOT NULL DEFAULT 0,
    ranged_attack_power INTEGER NOT NULL DEFAULT 0,
    health INTEGER NOT NULL DEFAULT 0,
    base_health INTEGER NOT NULL DEFAULT 0,
    mana INTEGER NOT NULL DEFAULT 0,
    base_mana INTEGER NOT NULL DEFAULT 0,
    strength INTEGER NOT NULL DEFAULT 0,
    agility INTEGER NOT NULL DEFAULT 0,
    stamina INTEGER NOT NULL DEFAULT 0,
    intellect INTEGER NOT NULL DEFAULT 0,
    spirit INTEGER NOT NULL DEFAULT 0,
    armor INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS creature_model_info (
    modelid INTEGER PRIMARY KEY NOT NULL,
    bounding_radius REAL NOT NULL DEFAULT 0,
    combat_reach REAL NOT NULL DEFAULT 0,
    gender INTEGER NOT NULL DEFAULT 2
);
CREATE TABLE IF NOT EXISTS spawns_creatures (
    spawn_id INTEGER PRIMARY KEY AUTOINCREMENT,
    spawn_entry1 INTEGER NOT NULL DEFAULT 0,
    map INTEGER NOT NULL DEFAULT 0,
    position_x REAL NOT NULL DEFAULT 0,
    position_y REAL NOT NULL DEFAULT 0,
    position_z REAL NOT NULL DEFAULT 0,
    orientation REAL NOT NULL DEFAULT 0,
    health_percent REAL NOT NULL DEFAULT 100,
    mana_percent REAL NOT NULL DEFAULT 100,
    movement_type INTEGER NOT NULL DEFAULT 0,
    spawn_flags INTEGER NOT NULL DEFAULT 0,
    ignored INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS spawns_gameobjects (
    spawn_id INTEGER PRIMARY KEY AUTOINCREMENT,
    spawn_entry INTEGER NOT NULL DEFAULT 0,
    spawn_map INTEGER NOT NULL DEFAULT 0,
    spawn_positionX REAL NOT NULL DEFAULT 0,
    spawn_positionY REAL NOT NULL DEFAULT 0,
    spawn_positionZ REAL NOT NULL DEFAULT 0,
    spawn_orientation REAL NOT NULL DEFAULT 0,
    spawn_rotation0 REAL NOT NULL DEFAULT 0,
    spawn_rotation1 REAL NOT NULL DEFAULT 0,
    spawn_rotation2 REAL NOT NULL DEFAULT 0,
    spawn_rotation3 REAL NOT NULL DEFAULT 0,
    spawn_animprogress INTEGER NOT NULL DEFAULT 0,
    spawn_state INTEGER NOT NULL DEFAULT 0,
    spawn_flags INTEGER NOT NULL DEFAULT 0,
    ignored INTEGER NOT NULL DEFAULT 0
);
`

const dbcSchema = commonSchema + `
CREATE TABLE IF NOT EXISTS ChrRaces (
    ID INTEGER PRIMARY KEY NOT NULL,
    FactionID INTEGER NOT NULL DEFAULT 0,
    MaleDisplayId INTEGER NOT NULL DEFAULT 0,
    FemaleDisplayId INTEGER NOT NULL DEFAULT 0,
    BaseLanguage INTEGER NOT NULL DEFAULT 0,
    CreatureType INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS AreaTable (
    ID INTEGER PRIMARY KEY NOT NULL,
    AreaNumber INTEGER NOT NULL DEFAULT 0,
    ContinentID INTEGER NOT NULL DEFAULT 0,
    ParentAreaNum INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS CreatureDisplayInfo (
    ID INTEGER PRIMARY KEY NOT NULL,
    ModelID INTEGER NOT NULL DEFAULT 0,
    CreatureModelScale REAL NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS EmotesText (
    ID INTEGER PRIMARY KEY NOT NULL,
    EmoteID INTEGER NOT NULL DEFAULT 0
);
`
